modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Igneko/vortech-embers-glory-kills/issues"

[[mods]]
# El ID debe ser exactamente igual al que pusimos en GloryKillsMod.java
modId="vortech_embers"
version="1.0.0"
displayName="Vortech Embers - Glory Kills"
authors="Igneko, Cowboy Vortech"
description='''
Una extensión visceral y trepidante para TACZ. 
Añade mecánicas de ejecución (Glory Kills) a los enemigos con poca salud, 
recompensando la agresión con curación y efectos de estado.
'''

# Dependencia obligatoria de Forge
[[dependencies.vortech_embers]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

# Dependencia obligatoria de Minecraft
[[dependencies.vortech_embers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"